import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'

const Home = () => {
  const [fruitToAdd, setFruitToAdd] = useState("")
  const [fruits, setFruits] = useState([
    {
      name: "apple"
    }, 
    {
      name: "orang"
    }
  ])

  const handleAdd = (fruit) => {
    setFruits([...fruits, { name: fruit }])
  }

  useEffect(() => {
    console.log(fruitToAdd)
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input onChange={(e) => setFruitToAdd(e.target.value)}></input>
        <button onClick={() => handleAdd(fruitToAdd)}>Add fruit</button>
        <div>
          <ul className='fruits'>
            {fruits.map(fruit => <li key={fruit.name}>{fruit.name}</li>)}
          </ul>
        </div>
      </main>

    </div>
  )
}

export default Home
